apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-challenge

resources:
  - deploy.yaml
  - hpa.yaml
  - ingress.yaml
  - namespace.yaml
  - quota.yaml
  - svc.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    strategy.spinnaker.io/versioned: "false"